In [1]:
import pandas as pd
import numpy as np
import pickle
import re

In [2]:
df = pd.read_csv("../data/outputs/invoice_numbers_fixed_last.csv")

In [3]:
df.rename(columns={
                "Invoice Number": "invoice_number",
                "Total Charged": "total_charged",
            }, inplace=True,)

In [4]:
df.total_charged.isna().sum()

1278

In [5]:
df.head()

  invoice_number  total_charged
0      X15688941     2755430.00
1      813728138       18004.67
2      G42174195       10245.21
3       27307572       20873.79
4      E37309831       32837.29

In [6]:
std_output = [
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/116065291.jpg', '116065291', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-02-19_6251.jpg', None, 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-04-04_4821.jpg', '18439230', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-04-28_5459.jpg', 'D35131951', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-05-06_5734.jpg', 'Q86400197', 'Total: -$3,575.8:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-05-17_2523.jpg', '337930077', 'Total: $1:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-05-30_7105.jpg', '422675770', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-06-08_5137.jpg', None, 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-06-13_1629.jpg', None, 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-06-15_7257.jpg', 'H49091391', 'Total: $1:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-07-19_6100.jpg', 'T58913932', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-08-11_8394.jpg', 'G43307344', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-09-04_6472.jpg', 'N05119842', 'Total: $:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-09-06_2824.jpg', 'W46992973', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-09-17_7562.jpg', 'T56434348', 'Total: $21,6!'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-10-14_3632.jpg', 'R25159687', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2021-12-17_704.jpg', 'R88280613', 'Total: $1l,921.19'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2022-02-19_7770.jpg', 'R49022919', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2022-04-29_4966.jpg', '311528310', 'Total: $27,4i'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2022-05-13_2460.jpg', '664522754', 'Total: $'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2022-05-27_1941.jpg', '979283277', 'Total: $.'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2022-05-28_4770.jpg', '813487968', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2022-06-21_226.jpg', '220394393', 'Total: $9,99!'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2022-06-26_7727.jpg', '760173368', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2022-07-02_1036.jpg', 'C38624807', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2022-07-05_3556.jpg', '719893326', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2022-10-30_504.jpg', '835843019', 'Total: $33,1:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2023-02-17_1761.jpg', 'J83789817', 'Total: $16,255.f'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2023-03-12_3069.jpg', '327525923', 'Total:630'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2023-03-27_913.jpg', 'U75994515', 'Total: $53,066:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2023-04-03_1534.jpg', '931101666', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2023-04-29_3770.jpg', '327952333', 'Total: $'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/2023-05-17_8049.jpg', '643467761', 'Total: $12,985.7{'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/224430200.jpg', '224430200', 'Total: $37,:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/227224377.jpg', '227224377', 'Total: $]'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/355212809.jpg', '355212809', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/373313006.jpg', '373313006', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/520260634.jpg', '520260634', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/725748905.jpg', '725748905', 'Total: $26,:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/765042909.jpg', '765042909', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/773674009.jpg', '773674009', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/825708962.jpg', '825708962', 'Total: $20,9:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/860655077.jpg', '860655077', 'Total: $37,75!'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/862115473.jpg', '862115473', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/877943921.jpg', None, 'Total: $2I'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/9121602.jpg', '9121602', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/986973581.jpg', '986973581', 'Total: $61,57;'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/991001106.jpg', '991001106', 'Total: $20,5;'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/A24802979.jpg', 'A24802979', 'Total: $'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/AndersonCarterandWhitaker_2021-11-15.jpg', None, 'Total: $10;;'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/CampbellWrightandColeman_2021-06-24.jpg', None, 'Total: $33,083.('),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/ChristianLevine_2022-09-25.jpg', '487742506', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/CowanLevyandDavis_2021-02-24.jpg', 'Z89958148', "Total: $7,604.1'"),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/DaughertyDavisandSampson_2023-03-31.jpg', '953436099', 'Total: $44,840.0('),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/E30166544.jpg', 'E30166544', 'Total: $11,321./'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2021-04-18_6182.jpg', '632846262', 'Total: ${'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2021-07-07_3401.jpg', 'J81924925', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2021-07-12_8068.jpg', '77595268', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2021-09-11_7504.jpg', 'T18503666', 'Total: $37,04!'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2022-01-15_8410.jpg', 'E26231313', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2022-02-11_7803.jpg', None, 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2022-03-14_2818.jpg', 'X31312836', 'Total: $'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2022-03-22_5135.jpg', 'X09986496', 'Total: $21,89;'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2022-04-07_3548.jpg', '330924852', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2022-04-11_27.jpg', 'G56427813', 'Total: $21,5('),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2022-04-18_1117.jpg', 'M92216175', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2022-06-25_2896.jpg', '28668595', 'Total: $21,866.€'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2022-08-02_4227.jpg', '835007915', 'Total: $;'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2022-08-07_8325.jpg', '136267398', 'Total: $'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2022-08-23_3485.jpg', '3236057', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2023-02-13_3223.jpg', 'T15780799', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2023-02-14_610.jpg', '385264182', 'Total: $I'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2023-02-23_6936.jpg', 'T25347129', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2023-03-05_1089.jpg', '575109766', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2023-03-08_8178.jpg', None, 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2023-03-10_1519.jpg', '949263417', 'Total: $21,362.2:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2023-05-09_2427.jpg', '752851804', 'Total: $55,!'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Email_Attachment_2023-05-16_3863.jpg', 'C76112130', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/FarleyLLC_2021-04-28.jpg', 'R89471651', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/FieldsGibson_2021-11-19.jpg', 'Y95827937', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/GallagherSolis_2021-03-30.jpg', '642086703', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/HartmanBarkerandGarcia_2021-09-04.jpg', '32446707', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/HesterRamirezandJimenez_2022-10-04.jpg', '42048821', 'Total: $32,='), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/HowardWoods_2022-10-17.jpg', '65912996', 'Total: $14,656.('),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/HughesMolinaandKennedy_2022-10-25.jpg', '835445770', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_1062.jpg', 'Y90063173', 'Total: $'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_1071.jpg', 'P97658206', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_1479.jpg', '416956786', 'Total: $'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_1503.jpg', 'R28106914', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_1864.jpg', '420519466', 'Total: $24,31;'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_2236.jpg', '605931331', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_3049.jpg', '166823673', 'Total: $9,782.;'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_3137.jpg', '876185164', 'Total: $65,2:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_3178.jpg', '822938021', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_3278.jpg', 'A91245929', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_3402.jpg', None, 'Total: $99,457 .'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_3629.jpg', 'Z10713986', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_3656.jpg', None, 'Total: $:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_3932.jpg', '355485626', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_4229.jpg', '73409823', 'Total: $'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_4357.jpg', '423531029', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_4769.jpg', None, 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_4927.jpg', '992283239', 'Total: $'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_4989.jpg', '302641442', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_5515.jpg', '825486934', 'Total: $25,779.7:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_5568.jpg', 'X87475967', 'Total: $'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_5636.jpg', '347457990', 'Total: $'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_5919.jpg', '482891702', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_5977.jpg', None, 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_5985.jpg', 'P56603990', 'Total: $'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_630.jpg', 'H35677554', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_6813.jpg', 'P00976444', 'Total: $:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_6947.jpg', '441360782', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_7156.jpg', 'G87374014', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_7294.jpg', 'F96608585', 'Total: $11,092:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_7332.jpg', 'J64684453', 'Total: $16,/'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_7367.jpg', '150189843', 'Total: $'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_7714.jpg', None, 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_772.jpg', 'J51177512', 'Total: $42,2;'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_7827.jpg', '871568454', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_7843.jpg', 'X21711068', 'Total: $;'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_8138.jpg', 'F39119263', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_902.jpg', 'W73044264', "Total: $83,970'"),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Incoming_inv_ParaisurZ996560_98.jpg', '195621415', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (1597).jpg', None, 'Total: $49,654,2('),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (1733).jpg', 'R70096617', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (2019).jpg', '988726016', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (2250).jpg', None, 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (2632).jpg', '491131511', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (2653).jpg', '339441236', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (3459).jpg', '611250061', 'Total: $22,842:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (3461).jpg', '836704930', 'Total: $4C'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (3537).jpg', '868297959', 'Total: $'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (37).jpg', '544235753', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (380).jpg', 'W39290560', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (3859).jpg', None, 'Total: $'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (4067).jpg', 'F44219757', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (4246).jpg', 'N38810174', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (4272).jpg', None, 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (4473).jpg', '978221149', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (4686).jpg', '919420457', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (4759).jpg', '189139192', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (4793).jpg', 'R42266451', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (5266).jpg', 'C25861568', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (570).jpg', '613440155', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (5966).jpg', None, 'Total: $32,!'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (640).jpg', '133674207', 'Total: $59,595/'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (6929).jpg', 'K24145918', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (744).jpg', 'V81905273', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (7662).jpg', '590658070', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (7731).jpg', '113077016', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (7802).jpg', None, 'Total: $19,115.:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (787).jpg', None, 'Total: $18,6;'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (82).jpg', '798373233', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Invoice (833).jpg', '645187376', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/J84103907.jpg', 'J84103907', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/L21090415.jpg', 'L21090415', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/LawrenceMooreandRollins_2022-05-05.jpg', 'D23588185', 'Total: $21,096.:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/LoveLLC_2023-04-29.jpg', '185501314', 'Total: $23,682.1!'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/M76986227.jpg', 'M76986227', 'Total: $]'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/M85871524.jpg', 'M85871524', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/MacdonaldCrawford_2022-07-04.jpg', '522428740', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/MarksInc_2021-02-17.jpg', '959936832', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/MartinezInc_2021-06-13.jpg', '571042494', 'Total: $1:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/MartinezPLC_2021-12-05.jpg', '669451383', 'Total: $:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/MasseyRamos_2022-05-15.jpg', '328749489', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/MckinneyLLC_2021-03-30.jpg', '201256504', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/MolinaandSons_2023-04-07.jpg', '244926579', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/MyersPLC_2022-01-05.jpg', '114330690', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/NelsonandSons_2022-08-05.jpg', 'Y20423468', 'Total: $€'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/P82919972.jpg', 'P82919972', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/PattersonWilson_2022-06-07.jpg', None, 'Total: $33,57]'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/PerezPLC_2021-07-23.jpg', '471728107', 'Total:'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/R99129371.jpg', 'R99129371', "Total: $'"), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/RomanInc_2021-04-01.jpg', 'Z96059104', 'Total: $65,373.4.jpg'), 
    ('D:/paraisur_eci_uba/datadSons_2022-11-15.jpg', None, 'Total: $18,17;'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/SantosLLC_202g', 'E22390057', 'Total: $'),
    ('D:/pa1-04-20.jpg', '745099541', 'Total: $;'),
    ('D:/paraisur_eci_uba/data/inpC_2021-02-09.jpg', 'E22390057', 'Total: $'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Smiputs/invoices/jpgs/StoneWelchandFrancthGroup_2022-02-12.jpg', 'X65732317', 'Total: $15,917,!'),
    ('D:/paraisur_eci_uba/data/inputs/invs/SwansonWallace_2021-02-12.jpg', '112305922', 'Total:'), 
    ('D:/paraisur_eci_uba/davoices/jpgs/StoneWelchandFranco_2022-12-15.jpg', '939985256', 'Total: $22,6;'),
    ('D:/paraisur_ec/paraisur_eci_uba/data/inputs/invoicei_uba/data/inputs/invoices/jpgs/SwansonWallace_2021-02-12.jpg', 'Y76142707', 'Total:'),
    ('D:/pars/V18849890.jpg', 'V18849890', 'Total:'),
    ('D:/paraisur_ei_uba/data/inputs/invoices/jpgs/ThorntonAnderson_2021-09-10.jpg', 'Y03231690', 'Total: $22,784'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/U65119576.jpg', 'U65119576', 'Total: $:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/V18849890.jpg', 'V18849890', 'Total: $51,689.5*'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/WallHart_2021-12-21.jpg', None, 'Total: $49,292.5;'), 
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/WilsonGroup_2021-10-16.jpg', 'B08075350', 'Total: $'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Y31660935.jpg', 'Y31660935', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Z29046653.jpg', 'Z29046653', 'Total:'),
    ('D:/paraisur_eci_uba/data/inputs/invoices/jpgs/Z47518912.jpg', 'Z47518912', 'Total: $')]

In [7]:
len(std_output)

192

In [8]:
import re

entrada = "12,985.7{"
expresion_regular = r"[,{\s}]"
salida = re.sub(expresion_regular, "", entrada)

print(salida)

12985.7

In [9]:
chars = [("$", ""), (":", ""), ("i", ""), ("!", ""), ("l,", "1"), (".f", ""),
        ("{", ""), ("./", ""), ("(", ""), ("'", ""), (";", ""), (",=", ""), (".jpg", ""),
        ("*", ""), (".€", ""), ("/", ""), ("]", ""), ("C", ""), ("€", ""), ("I", ""), (" .", ""), (". ", ""),
        ("-.", ""), ("..", ""), ("--", ""), (".-", "")]

cant = 0
cant_eq = 0

for output in std_output:
    path, invoice_number, total_charged = output
    if invoice_number:
        splitted = total_charged.split(": ")
        if len(splitted) > 1:
            value = splitted[1]
            for char, rep in chars:
                value = value.replace(char, rep)
            if len(value) == 1:
                value = value.replace(".", "")
            if len(value) > 4:
                value = value.replace(",", "")
            else:
                value = value.replace(",", ".")
            if value:
                cant += 1
                value = float(value)
                total = df.loc[df['invoice_number'] == invoice_number, 'total_charged'].values[0]
                equals = value == total
                if equals:
                    cant_eq += 1
                else:
                    df.loc[df['invoice_number'] == invoice_number, 'total_charged'] = value

print(f'Cantidad de items corregidos: {cant - cant_eq}')

Cantidad de items corregidos: 0

In [10]:
df.describe()

       total_charged
count   7.133000e+03
mean    1.018076e+05
std     1.230620e+06
min    -5.165390e+07
25%     1.448414e+04
50%     2.337490e+04
75%     3.641124e+04
max     5.437558e+07

In [11]:
with open ('../data/outputs/save_errors_1689928271.txt', 'rb') as fp:
    saved_errors = pickle.load(fp)

In [12]:
for input_path, invoice_number, result in saved_errors:
    total_charged = 0
    flag = False
    for res in result:
        expresion_regular = r"[-$\d,.]+"
        salida = "".join(re.findall(expresion_regular, res[1]))
        if (("," in salida or "." in salida) and 
            ("date" not in res[1].lower()) and ("mountain" not in res[1].lower())):
            if len(salida) > 8:
                continue
            if len(salida) > 7:
                salida = salida.replace(",", "")
            else:
                salida = salida.replace(",", ".")
            
            for char, rep in chars:
                salida = salida.replace(char, rep)
            if len(salida) == 1:
                salida = salida.replace(".", "")
            if salida:
                expresion_regular = r"\d+\.\d+(\.\d+)+"
                cont = re.findall(expresion_regular, salida)
                if len(cont) > 0:
                    continue
                    
                expresion_regular = r"\d{4}\.\d{2}-"
                cont_2 = re.findall(expresion_regular, salida)
                if len(cont_2) > 0:
                    continue
                    
                if salida.count('.') > 1:
                    continue           
                
                expresion_regular = r"\d+(?:\.\d+)?-"
                cont_3 = re.findall(expresion_regular, salida)
                if len(cont_3) > 0:
                    continue
                
                salida = float(salida)
                total_charged += salida
                flag = True
    if flag:
        df.loc[df['invoice_number'] == invoice_number, 'total_charged'] = total_charged

In [13]:
df.total_charged.isna().sum()

1099

In [14]:
df.describe()

       total_charged
count   7.312000e+03
mean    2.774322e+05
std     2.146641e+06
min    -5.165390e+07
25%     1.473364e+04
50%     2.388983e+04
75%     3.770795e+04
max     5.924565e+07

In [15]:
df.rename(columns={
                "invoice_number": "Invoice Number",
                "total_charged": "Total Charged",
            }, inplace=True,)

In [16]:
df.to_csv('../data/outputs/invoice_numbers_last_final_with_nan.csv', index=False)